openapi: 3.0.0
info:
  version: 0.0.0
  title: lol-tracker
  description: track user activity and their performance

paths:
  /lol/activity:
    post:
      description: adds a user activity to the system
      operationId: app.add_activity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LOLActivity'
      responses:
        "201":
          description: "user activity added"
        "404":
          description: "invalid input"
  /lol/match:
    post:
      description: adds a match result to the system
      operationId: app.add_match
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LOLMatch'
      responses:
        "201":
          description: "match added"
        "404":
          description: "invalid input"

components:
  schemas:
    LOLActivity:
      required:
      - user_id
      - region
      - login_counts
      - timestamp
      - trace_id
      type: object
      properties:
        user_id:
          type: string
          description: user in game name
          format: uuid
          example: u-d290f1ee-6c54-4b01-90e6-d701748f0851
        region:
          type: string
          description: server location
          example: EUW
        login_counts:
          type: integer
          description: number of login counts per week
          example: 3
        timestamp:
          type: string
          description: last time user login
          format: date-time
          example: "2025-04-24 06:24:09.856 -07:00"
        trace_id:
          type: string
          format: uuid
          description: trace id in string
          example: 1cd6745a-8a47-4894-9bb4-fd4b877e0b70
        
    LOLMatch:
      required:
      - match_id
      - user_id
      - kill
      - death
      - assist
      - timestamp
      - trace_id
      type: object
      properties:
        match_id:
          type: string
          format: uuid
          example: m-d290f1ee-6c54-4b01-90e6-d701748f0851
        user_id:
          type: string
          description: user in game name
          format: uuid
          example: u-d290f1ee-6c54-4b01-90e6-d701748f0851
        kill:
          type: integer
          description: number of kills in the game
          example: 5
        death:
          type: integer
          description: number of deaths in the game
          example: 5
        assist:
          type: integer
          description: number of assists in the game
          example: 5
        timestamp:
          type: string
          description: time of starting match
          format: date-time
          example: "2025-04-24 06:24:09.856 -07:00"
        trace_id:
          type: string
          description: trace id in string
          format: uuid
          example: 1cd6745a-8a47-4894-9bb4-fd4b877e0b70