state:
  file: data/processing/data.json
  default: {
    "num_activities": 0,
    "num_matches": 0,
    "max_login_counts": 0,
    "avg_kill": 0,
    "last_updated": "1999-01-01T12:00:00.000-07:00"
  }
scheduler:
  interval: 5
urls:
  activity: http://storage:8090/storage/lol/activity
  match: http://storage:8090/storage/lol/match