services:
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: riot
      MYSQL_PASSWORD: riot
      MYSQL_DATABASE: riot
      TZ: US/Pacific
    ports:
      - 3306:3306



